name: Trigger auto deployment for verbose-waffle

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/verbose-waffle-AutoDeployTrigger-a34c8724-aaf1-4629-aa58-9f77739f860c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: zp5njqlfex.azurecr.io
          username: ${{ secrets.VERBOSEWAFFLE_REGISTRY_USERNAME }}
          password: ${{ secrets.VERBOSEWAFFLE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zp5njqlfex.azurecr.io/verbose-waffle:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VERBOSEWAFFLE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n verbose-waffle -g verbose-waffle --server zp5njqlfex.azurecr.io --username  ${{ secrets.VERBOSEWAFFLE_REGISTRY_USERNAME }} --password ${{ secrets.VERBOSEWAFFLE_REGISTRY_PASSWORD }}
            az containerapp update -n verbose-waffle -g verbose-waffle --image zp5njqlfex.azurecr.io/verbose-waffle:${{ github.sha }}
